"""add publish_log tables

Revision ID: ab2519737295
Revises: 
Create Date: 2026-09-08 16:24:04.343841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab2519737295'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('publish_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ig_content_id', sa.String(), nullable=False),
    sa.Column('destination', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('permalink', sa.String(), nullable=True),
    sa.Column('channel', sa.String(), nullable=True),
    sa.Column('published_by', sa.String(), nullable=True),
    sa.Column('snapchat_media_id', sa.String(), nullable=True),
    sa.Column('snapchat_request_id', sa.String(), nullable=True),
    sa.Column('posted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ig_content_id', 'destination', 'source', name='uq_publish_log_content_dest_source'),
    schema='snapchat'
    )
    op.create_index(op.f('ix_snapchat_publish_log_ig_content_id'), 'publish_log', ['ig_content_id'], unique=False, schema='snapchat')
    op.create_table('publish_log_snaps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('publish_log_id', sa.Integer(), nullable=False),
    sa.Column('snap_index', sa.Integer(), nullable=False),
    sa.Column('snapchat_media_id', sa.String(), nullable=False),
    sa.Column('snapchat_request_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['publish_log_id'], ['snapchat.publish_log.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='snapchat'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('publish_log_snaps', schema='snapchat')
    op.drop_index(op.f('ix_snapchat_publish_log_ig_content_id'), table_name='publish_log', schema='snapchat')
    op.drop_table('publish_log', schema='snapchat')
    # ### end Alembic commands ###
